AllCops:
  Exclude:
    - '**/schema.rb'
  RunRailsCops: true

Documentation:
  Enabled: false

FileName:
  Exclude:
    - bin/who-to-blame

MethodLength:
  Max: 13

Output:
  Exclude:
    - bin/*
    - lib/who_to_blame/runner.rb

TrailingComma:
  EnforcedStyleForMultiline: comma
