AllCops:
  Exclude:
    - '**/schema.rb'
  RunRailsCops: true

Documentation:
  Enabled: false

FileName:
  Exclude:
    - bin/who-to-blame

Output:
  Exclude:
    - bin/*
    - lib/who_to_blame/runner.rb
