language: ruby
rvm:
  - 2.0.0
before_install:
  - npm install jshint
install:
  - bundle install
before_script:
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare
script:
  - bundle exec rake
  - rubocop -D
  - travis-lint
  - gem build who_to_blame.gemspec
  - jshint app/assets/javascripts/who_to_blame/*
  - jshint spec/javascripts/who_to_blame/*
  - jshint spec/javascripts
  - bundle exec teaspoon
